_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "FXGeneralizedRCNN"
  WEIGHTS: "/home/hugo/bdd100k-monitoring/monitoring-interface/models/weights/model_final_resnet_bdd.pth"
#  WEIGHTS: "./data/VOC-Detection/faster-rcnn/faster_rcnn_R_50_FPN_all_logistic/random_seed_0/model_final.pth"

#  PROPOSAL_GENERATOR:
#    NAME: "RPNLogistic"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "StandardROIHeads"
    NUM_CLASSES: 10
    SCORE_THRESH_TEST: 0.4024
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('bddd_custom_train',)
  TEST: ('bdd_custom_val',)
SOLVER:
  IMS_PER_BATCH: 30
  BASE_LR: 0.02
  STEPS: (1750, 2300)
  MAX_ITER: 7000  # 40 epochs
  WARMUP_ITERS: 25
DATALOADER:
    NUM_WORKERS: 8  # Depends on the available memory